version: "2.4"
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./hosts:/etc/nginx/http.d
      - ./www:/var/www
    depends_on:
      - app
  app:
    build: ./app
    volumes:
      - ./www:/var/www
      - ./fpm:/etc/php8/php-fpm.d
