version: "2.4"
services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
    depends_on:
      - php
  php:
    build: ./app
    volumes:
      - ./www:/var/www
